# yaml-language-server: $schema=https://raw.githubusercontent.com/dimfeld/llmutils/main/schema/rmfilter-config-schema.json
edit-format: diff
copy: true
quiet: false
docs: []
rules: []
gitroot: true
commands:
  - globs:
    - src/rmfind.ts
    - src/common
    with-imports: true
    grep: []
    whole-word: false
    expand: false
instructions: |
  When no grep terms are provided, but a query is provided, generate grep terms from the query usng a language model.
  Then find all files in the baseDir that match any of the grep terms and proceed as usual.

