[test]
preload = ["./test-preload.ts"]
# Ignore sveltekit tests which need to run in vitest
# eventually we'll just move everything to vitest so we can run all tests at once.
pathIgnorePatterns = ["src/lib/**", "src/routes/**"]

