version: '3.8'

services:
  llmutils-bot:
    build: .
    image: llmutils-bot:latest
    container_name: llmutils-bot
    restart: unless-stopped

    ports:
      - '3000:3000'

    volumes:
      # Persistent data storage
      - ./data:/data
      # Mount config files if needed
      - ./.rmfilter:/app/.rmfilter:ro

    environment:
      # GitHub Configuration
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}

      # Discord Configuration
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}

      # Database Configuration
      - DATABASE_PATH=/data/bot.db

      # Workspace Configuration
      - WORKSPACE_BASE_DIR=/data/workspaces
      - WORKSPACE_RETENTION_DAYS=${WORKSPACE_RETENTION_DAYS:-7}

      # Logging Configuration
      - LOG_RETENTION_DAYS=${LOG_RETENTION_DAYS:-7}
      - LOG_LEVEL=${LOG_LEVEL:-info}

      # Server Configuration
      - BOT_SERVER_PORT=3000

      # Admin Configuration
      - ADMIN_DISCORD_USER_IDS=${ADMIN_DISCORD_USER_IDS}

      # Cleanup Service Configuration
      - CLEANUP_INTERVAL_HOURS=${CLEANUP_INTERVAL_HOURS:-6}
      - MAX_CONCURRENT_TASKS=${MAX_CONCURRENT_TASKS:-5}

      # Model Configuration
      - DEFAULT_MODEL=${DEFAULT_MODEL:-google/gemini-2.5-pro-latest}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}

    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  data:
    driver: local
