---
# yaml-language-server: $schema=https://raw.githubusercontent.com/dimfeld/llmutils/main/schema/rmplan-plan-schema.json
title: Integrate Permissions MCP into the Claude Code Executor
goal: Modify the `ClaudeCodeExecutor` to use the new permissions MCP when enabled.
id: 56
uuid: 221d894e-8097-4e26-bf9f-0d5caa416d45
status: done
priority: high
dependencies:
  - 55
issue:
  - https://github.com/dimfeld/llmutils/issues/94
docs:
  - docs/tutorials/claude-permissions-mcp.md
planGeneratedAt: 2025-06-07T09:18:47.448Z
promptsGeneratedAt: 2025-06-07T20:36:58.810Z
createdAt: 2025-06-07T02:05:26.354Z
updatedAt: 2025-10-27T08:39:04.268Z
project:
  title: Implement Interactive Permissions for Claude Code Executor
  goal: Allow the user to respond to tool permissions requests when using the
    Claude Code executor.
  details: This project will add support for the Claude Code SDK's permissions MCP
    (Model Context Protocol). A new MCP server will be implemented to handle
    permission requests by prompting the user for confirmation. This feature
    will be configurable via a new flag in `claudeCodeOptionsSchema` and an
    environment variable. When enabled, the executor will dynamically generate
    the necessary MCP configuration and launch the Claude Code CLI with the
    appropriate settings to enable interactive tool-use permissions.
tasks:
  - title: Add Configuration Option to Enable Permissions MCP
    done: true
    description: Modify the `claudeCodeOptionsSchema` in
      `src/rmplan/executors/claude_code.ts` by adding a new optional boolean
      field named `enablePermissionsMcp`. This will allow users to enable the
      feature via their `rmplan.json` configuration.
  - title: Implement MCP Activation Logic
    done: true
    description: In the `execute` method of the `ClaudeCodeExecutor`, add logic to
      check if the `enablePermissionsMcp` option is true or if the
      `CLAUDE_CODE_MCP` environment variable is set. This will determine whether
      to activate the permissions flow for the current execution.
  - title: Implement Dynamic MCP Configuration File Generation
    done: true
    description: When the permissions MCP is activated, write a temporary JSON
      configuration file to disk. This file will instruct the Claude Code CLI
      how to start our permissions server, specifying the command (e.g., `bun`)
      and the path to the `permissions_mcp.ts` script. The path to the script
      must be resolved correctly from the executor's location.
  - title: Update Claude Code CLI Arguments
    done: true
    description: If the permissions MCP is active, modify the arguments passed to
      the `claude` CLI. Add the `--mcp-config` flag with the path to the
      temporary configuration file and the `--permission-prompt-tool` flag to
      tell Claude Code which tool to use for permission checks (e.g.,
      `mcp__permissions__approval_prompt`).
  - title: Ensure Cleanup of Temporary Resources
    done: true
    description: Wrap the `claude` process execution in a `try...finally` block to
      ensure that the temporary MCP configuration file and its containing
      directory are deleted after the command finishes, regardless of its
      success or failure. This prevents cluttering the filesystem.
changedFiles:
  - docs/tutorials/claude-permissions-mcp.md
  - src/rmplan/executors/claude_code/permissions_mcp.ts
  - src/rmplan/executors/claude_code.ts
rmfilter:
  - src/rmplan/executors/claude_code.ts
---

With the permissions server script ready, this phase integrates it into the main `ClaudeCodeExecutor`. This involves adding configuration options, detecting when the feature should be active, and dynamically creating the necessary configuration file for the Claude Code CLI. The executor will be responsible for managing the lifecycle of this temporary configuration.
