---
# yaml-language-server: $schema=https://raw.githubusercontent.com/dimfeld/llmutils/main/schema/rmplan-plan-schema.json
title: Convert permissions MCP to stdio
goal: ""
id: 63
status: in_progress
priority: medium
docs:
  - https://bun.sh/guides/process/ipc
createdAt: 2025-06-10T08:02:56.765Z
updatedAt: 2025-06-10T21:05:31.978Z
tasks: []
---

Relevant Directory:
- src/rmplan/executors/claude_code

I think if you take too long to respond to the permissions prompt the HTTP connection times out maybe,
and so we should try running the MCP server in stdio mode instead of SSE instead.

We'll update the MCP server to communicate with the parent process over a unix socket with tool info
and responses. Then we remove our own spawning of the MCP server and let Claude Code do it instead by providing the path to the MCP server file.

The MCP server should send a message with the tool details when it gets a request, and the parent
process (the executor file) should then display the confirm prompt, and send the response back.

## Spawning and Communication

The issue here is that in this case we are not the ones spawning the MCP server, but it would be Claude code itself.

So I think what we need is to create a unix socket and pass its path as an argument to the MCP server specified in the MCP configuration file that we generate. And then we communicate with the MCP server using that.

## MCP Config

The new generated MCP Config file should look like

```
const mcpConfig = {
  mcpServers: {
    permissions: {
      type: 'stdio',
      command: [
        'bun',
        path.join(__dirname, 'claude_code', 'permissions-mcp.ts'),
        unixSocketPath
      ]
    },
  },
};
```
