---
# yaml-language-server: $schema=https://raw.githubusercontent.com/dimfeld/llmutils/main/schema/rmplan-plan-schema.json
goal: Implement a feature for `answer-pr` to automatically detect the relevant
  Pull Request (PR) from the current Git or Jujutsu branch if no PR identifier
  is provided. Additionally, warn the user if an explicitly provided PR number
  doesn't match the current branch.
id: 15
uuid: d50dd1c0-fa99-45d1-90f9-7bc955e9929d
status: done
updatedAt: 2025-10-27T08:39:04.288Z
tasks:
  - title: 1. Implement SCM Current Branch Detection Utilities
    done: true
    description: Create utility functions to get the current branch name from Git
      and Jujutsu. Then, create a combined function that tries both.
  - title: 2. Implement Fetching Open Pull Requests
    done: true
    description: Add a function to fetch all open pull requests for a given repository.
  - title: 3. Modify `answer-pr` Command for Optional PR Identifier
    done: true
    description: Update the `commander` definition for `answer-pr` to make the
      `prIdentifier` argument optional.
  - title: 4. Implement PR Autodetection and Selection Logic
    done: true
    description: >
      Modify `handleRmprCommand` in `src/rmpr/main.ts` to implement the PR
      autodetection and selection flow when no PR identifier is explicitly
      provided.
  - title: 5. Implement Branch Mismatch Warning
    done: true
    description: If a PR identifier was explicitly provided, warn the user if the
      current SCM branch does not match the PR's head branch.
---

The `answer-pr` command currently requires a PR identifier (URL or number). This project will enhance it to:
1.  Determine the current local branch name, supporting both Git and Jujutsu (jj) SCMs.
2.  Fetch a list of open PRs from GitHub for the current repository.
3.  If `answer-pr` is invoked without a PR identifier:
    *   Attempt to find an open PR whose head branch name matches the current local SCM branch name.
    *   If a unique match is found, use that PR.
    *   If multiple matches are found, prompt the user to select one.
    *   If no match is found, prompt the user to select from all open PRs or enter an identifier manually.
4.  If `answer-pr` is invoked *with* a PR identifier:
    *   After fetching the PR details, compare the PR's head branch name with the current local SCM branch name.
    *   If they do not match, warn the user and ask for confirmation before proceeding.

This will improve the usability of `answer-pr` by reducing the need to manually look up PR numbers when working on a feature branch corresponding to a PR.
