# yaml-language-server: $schema=https://raw.githubusercontent.com/dimfeld/llmutils/main/schema/rmplan-plan-schema.json
id: 1llecrd
title: Test plan with options
goal: Goal to be defined.
details: Details to be added.
status: pending
createdAt: 2025-06-01T02:25:24.190Z
updatedAt: 2025-06-01T02:25:24.190Z
tasks: []
dependencies:
  - plan-123
  - plan-456
priority: high
