# yaml-language-server: $schema=../../schema/tim-config-schema.json

defaultExecutor: claude-code
planAutocompleteStatus: done
postApplyCommands:
  - title: Format JS
    command: bun run format
    allowFailure: true
    hideOutputOnSuccess: true
planning:
  instructions: docs/planning.md
review:
  customInstructionsPath: docs/reviewer-instructions.md
agents:
  reviewer:
    instructions: docs/reviewer-instructions.md
  implementer:
    instructions: docs/implementer-instructions.md
updateDocs:
  mode: after-iteration
  applyLessons: true
  exclude:
    - CHANGELOG and similar documents
workspaceCreation:
  cloneLocation: ..
  cloneMethod: mac-cow
  postCloneCommands:
    - title: Install Dependencies
      command: bun install
      # Can fail due to tree-sitter not building but that's fine since we're only using the WASM
      allowFailure: true
lifecycle:
  commands:
    - title: Install Dependencies
      command: bun install
      mode: run
      allowFailure: false
