---
# yaml-language-server: $schema=https://raw.githubusercontent.com/dimfeld/llmutils/main/schema/rmplan-plan-schema.json
title: Documentation and Refinement
goal: To ensure the new `add` and `split` commands are well-documented,
  user-friendly, and seamlessly integrated into the `rmplan` tool.
id: 26
uuid: c3f58928-c50e-4ec5-8763-7bcd4efd9a21
status: done
dependencies:
  - 25
references:
  "25": d5dd8c64-b455-420b-969c-aa7060ab5af8
planGeneratedAt: 2025-05-31T20:32:33.556Z
promptsGeneratedAt: 2025-06-01T08:09:33.849Z
createdAt: 2025-05-31T20:32:33.556Z
updatedAt: 2025-10-27T08:39:04.248Z
project:
  title: Enhance rmplan with `add` and `split` commands for improved plan creation
    and organization.
  goal: The overall goal of this project is to introduce two new commands, `add`
    and `split`, to the `rmplan` CLI tool. The `add` command will facilitate the
    quick creation of new, empty plan files. The `generate` command will be
    enhanced to populate these empty plans. The `split` command will enable
    users to break down large, existing plans into multiple, smaller phase-based
    plan files using an LLM.
  details: This project aims to improve the workflow of creating and managing
    complex project plans with `rmplan`. The `add` command will allow users to
    initialize a plan with a title and optional metadata like dependencies and
    priority. The `generate` command will then be able to take this stub plan
    and use an LLM to fill in the detailed tasks and steps, updating the
    existing file. The `split` command will address the need to break down
    large, already detailed plans. It will leverage an LLM to analyze the tasks
    within a single plan file and intelligently divide them into a sequence of
    new, phase-specific plan files, automatically inferring dependencies between
    these new phases. This enhancement will provide users with more flexibility
    in how they create and structure their plans, catering to both starting new
    plans from scratch and reorganizing existing ones.
tasks:
  - title: Update README.md with `add` and `split` command documentation.
    done: true
    description: >
      Add comprehensive documentation for the new `add` and `split` commands to
      the README.md file. The documentation should be added to the appropriate
      section of the README (likely under the rmplan commands section) and
      should include:

      - Clear descriptions of what each command does

      - All available command-line options with explanations

      - Multiple usage examples showing different scenarios

      - Any relevant notes or best practices

      - Integration with the existing documentation structure
  - title: Review and refine command-line help text and error messages.
    done: true
    description: >
      Review and improve the user-facing text for both the `add` and `split`
      commands. This includes:

      - Command descriptions shown in `rmplan --help`

      - Option descriptions and help text

      - Error messages for validation failures or edge cases

      - Success messages and progress indicators

      The goal is to ensure all text is clear, concise, and helpful for users.
changedFiles:
  - .rmfilter/config/rmplan.yml
  - CLAUDE.md
  - README.md
  - src/rmplan/executors/claude_code.ts
  - src/rmplan/id_utils.test.ts
  - src/rmplan/id_utils.ts
  - src/rmplan/plans.ts
  - src/rmplan/rmplan.ts
rmfilter:
  - src/rmplan
  - src/common
---

This final phase focuses on polishing the newly implemented features. It includes updating all relevant documentation, refining command-line help messages, and ensuring a smooth user experience.
